version: '3.8'

# Docker Compose override for local development
# This file is automatically merged with docker-compose.yml when you run docker-compose up
# To use this explicitly: docker-compose -f docker-compose.yml -f docker-compose.override.yml up

services:
  api:
    # Mount source code for hot reload (development only)
    volumes:
      - ./src/Api:/src/src/Api:ro
      - ./src/Application:/src/src/Application:ro
      - ./src/Domain:/src/src/Domain:ro
      - ./src/Infrastructure:/src/src/Infrastructure:ro
      - ./src/Contracts:/src/src/Contracts:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    # Enable debugging
    ports:
      - "8080:8080"
      - "5000:5000"  # Debugging port

  worker:
    volumes:
      - ./src/Worker:/src/src/Worker:ro
      - ./src/Application:/src/src/Application:ro
      - ./src/Domain:/src/src/Domain:ro
      - ./src/Infrastructure:/src/src/Infrastructure:ro
      - ./src/Document:/src/src/Document:ro
      - ./src/Events:/src/src/Events:ro
    environment:
      - DOTNET_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  # UI doesn't need hot reload as Blazor WASM is compiled into the image
  # For UI development, use `dotnet watch` locally instead

  # Development database GUIs
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: uservicedemo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - uservicedemo-network

  mongo-express:
    image: mongo-express:latest
    container_name: uservicedemo-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - uservicedemo-network
